name: Executar testes com PHPUnit

on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  run-phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Instalar dependências com o Composer
        run: composer install --prefer-dist --no-suggest
    
      - name: Executar o phpunit
        run: ./vendor/bin/phpunit
